#services:
#  elasticsearch-single:
#    image: elasticsearch:8.18.0
#    container_name: elasticsearch-single
#    environment:
#      - discovery.type=single-node
#      - ELASTIC_PASSWORD=password  # 设置Elasticsearch超级用户的密码
#      - xpack.security.enabled=true       # 启用安全模块
#    ports:
#      - "9200:9200"                       # 映射9200端口
#    volumes:
#      - esdata:/usr/share/elasticsearch/data
#
#volumes:
#  esdata:
#    driver: local




services:
  elasticsearch:
    image: elasticsearch:8.18.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=password
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
#      - xpack.security.http.ssl.enabled=true
#      - xpack.security.transport.ssl.enabled=true
#      - xpack.security.authc.api_key.enabled=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_certs:/usr/share/elasticsearch/config/certs
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic

  kibana:
    image: kibana:8.18.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
#      - ELASTICSEARCH_USERNAME=elastic
#      - ELASTICSEARCH_PASSWORD=password
#      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjpOUGFad0FPb1F5YUFKbHQyM0NlVlZ3
    volumes:
      - es_certs:/usr/share/kibana/config/certs
    ports:
      - "5601:5601"
    networks:
      - elastic

volumes:
  es_data:
    driver: local
  es_certs:
    driver: local

networks:
  elastic:
    driver: bridge