#version: '3'

services:
#  zookeeper:
#    image: wurstmeister/zookeeper:3.4.6
#    image: wurstmeister/zookeeper:latest
#    image: zookeeper:latest
#    ports:
#      - "2181:2181"

  kafka:
#    image: wurstmeister/kafka:latest
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
#      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://127.0.0.1:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      #      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      CLUSTER_ID: 5L6g3nShT-eMCtK--X86sw
#    depends_on:
#      - zookeeper