services:
  es00:
    image: elasticsearch:8.18.0
    container_name: es00
    environment:
      - node.name=es00
      - cluster.name=es-docker-cluster
      - node.roles=master,data
      - transport.port=9300
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es00
      - bootstrap.memory_lock=true # swapping, 应尽力避免swap,
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - xpack.security.authc.success_cache.enabled=true
      - ELASTIC_PASSWORD=password # 仅首次启动使用，后续通过API修改
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/es00.key
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/es00.crt
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca.crt
    volumes:
      - esdata00:/usr/share/elasticsearch/data
      - ./certs:/usr/share/elasticsearch/config/certs  # 挂载SSL证书
    ports:
      - "9210:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
  es01:
    image: elasticsearch:8.18.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - node.roles=master,data
      - transport.port=9300
      - discovery.seed_hosts=es00,es02
      - cluster.initial_master_nodes=es00
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - xpack.security.authc.success_cache.enabled=true
      - ELASTIC_PASSWORD=password
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/es01.key
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/es01.crt
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca.crt
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - ./certs:/usr/share/elasticsearch/config/certs
    ports:
      - "9220:9200"
    networks:
      - elastic
  es02:
    image: elasticsearch:8.18.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - node.roles=master,data,voting_only
      - transport.port=9300
      - discovery.seed_hosts=es00,es01
      - cluster.initial_master_nodes=es00
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - xpack.security.authc.success_cache.enabled=true
      - ELASTIC_PASSWORD=password
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/es02.key
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/es02.crt
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca.crt

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
      - ./certs:/usr/share/elasticsearch/config/certs
    ports:
      - "9230:9200"
    networks:
      - elastic

  kibana1:
    image: kibana:8.18.0
    container_name: kibana1
    depends_on:
      - es00
      - es01
      - es02
    environment:
     # - ELASTICSEARCH_HOSTS=[http://es00:9210,http://es01:9220,http://es02:9230]
      - ELASTICSEARCH_HOSTS=http://es00:9200
      - ELASTICSEARCH_REQUESTTIMEOUT=60000
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=*UszNgIqfcZs228Q5hdd
    #  - ELASTICSEARCH_SERVICEACCOUNTTOKEN= AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjo5NkNwUHRPWVRVQ3FEMTZBNFh6VGhB
      - SERVER_SSL_ENABLED=false
     # - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certs/kibana.csr
      #- SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certs/kibana.pem
      #- SERVER_SSL_KEY=/usr/share/kibana/config/certs/kibana.key
     # - SERVER_SSL_KEY=/usr/share/kibana/config/certs/kibana.key
     # - SERVER_READYTIMEOUT=120000
    volumes:
      - ./certs:/usr/share/kibana/config/certs  # 挂载SSL证书
    ports:
      - "5611:5601"
    networks:
      - elastic

volumes:
  esdata00:
    driver: local
  esdata01:
    driver: local
  esdata02:
    driver: local

networks:
  elastic:
    driver: bridge