services:
  zookeeper:
    image: zookeeper:3.8.4  # 推荐使用固定版本
    container_name: zoo
#    hostname: zookeeper
    ports:
      - "2181:2181"          # 客户端连接端口
      - "2888:2888"          # 节点间通信端口（单节点可不暴露）
      - "3888:3888"          # 选举端口（单节点可不暴露）
    environment:
      ZOO_MY_ID: 1           # 节点ID（单节点设为1）
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181  # 单节点配置
#      ZOO_MAX_CLIENT_CNXNS: 60  # 最大客户端连接数
      ZOO_STANDALONE_ENABLED: "true"  # 允许单机模式
    volumes:
      - ./data:/data         # 数据持久化
      - ./datalog:/datalog   # 事务日志
    restart: unless-stopped  # 自动重启