services:
  mysql2:
    image: mysql:8.0
    container_name: mysql
    restart: always
    privileged: true # 特权模式, 线上环境 慎用
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: canal
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test
      TZ: Asia/Dubai
      LANG: C.UTF-8
#    command:
#      - server_id=1 #主站ID
#      - log-bin=/var/lib/mysql/mysql-bin #开启binlog的文件名
#      - sync_binlog=1
#      - binlog-ignore-db=mysql
#      - binlog_format=ROW # binlog格式为ROW
#      - expire_logs_days=30 # binlog文件存活时间
#      - default-authentication-plugin=mysql_native_password
#      - character-set-server=utf8mb4
#      - collation-server=utf8mb4_general_ci
#      - explicit_defaults_for_timestamp=true
#      - lower_case_table_names=1
#      - sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    volumes:
      - ./mysql_data:/var/lib/mysql # 数据持久化
      - ./mysql/conf.d:/etc/mysql/conf.d  # 挂载 MySQL 的 Binlog 配置
#      - ./mysql/conf.d/my.cnf:/etc/my.cnf
    ports:
      - "43306:3306"
    networks:
      - canal_network

  canal-server:
    image: canal/canal-server:v1.1.8  # 使用官方镜像
    container_name: canal-server
    restart: always
    ports:
      - "11111:11111"  # Canal 默认端口
    volumes:
      - ./conf:/home/admin/canal-server/conf  # 挂载配置文件
      - ./logs-canal-server:/home/admin/canal-server/logs
    environment:
      - canal.auto.scan=true
      - canal.destinations=example # canal实例名称，根据自己喜好命名
      - canal.instance.mysql.slaveId=1085 # canal作为模仿从站的ID，不可与主站重复
      - canal.instance.master.address=127.0.0.1:43306 #mysql的连接地址
      - canal.instance.dbUsername=canal # mysql的用户
      - canal.instance.dbPassword=password # mysql的密码
      - canal.instance.connectionCharset=UTF-8
      - canal.instance.tsdb.enable=true
      - canal.instance.gtidon=false
      - canal.instance.parser.parallelThreadSize=16
      - canal.instance.filter.regex=test.* # 此处为监听的正则表达式过滤，具体参考官网配置，多个用英文逗号隔开",",例如：dbname.tablename1,dbname.tablename2
    depends_on:
      - mysql2
    networks:
      - canal_network

volumes:
  mysql_data:

networks:
  canal_network:
    driver: bridge