services:
  seata-server:
    image: seataio/seata-server:2.0.0
    container_name: seata-server-file
    hostname: seata-server
    ports:
      - "8091:8091"  # 控制台端口
      - "7091:7091"  # 服务端口
    environment:
#      - SEATA_IP=127.0.0.1  # 替换为实际IP或主机名
      - SEATA_PORT=8091
      - STORE_MODE=file  # 使用文件存储模式
#      - SEATA_CONFIG_NAME=file:/seata-server/resources/registry  # 配置文件路径
#    volumes:
#      - ./seata/config:/seata-server/resources  # 配置文件目录
#      - ./seata/data:/seata-server/sessionStore  # 会话数据持久化目录
    restart: unless-stopped
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://127.0.0.1:8091/actuator/health"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

