version: '3.8'

services:
  kibana:
    image: kibana:8.18.0  # 推荐指定版本
    container_name: kibana
    ports:
      - "5601:5601"  # Kibana默认端口
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # 指向Elasticsearch服务
      - SERVER_NAME=kibana.msb.com
#      - ELASTICSEARCH_USERNAME=elastic
#      - ELASTICSEARCH_PASSWORD=mypassword
#      - SERVER_SSL_ENABLED=true
#      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certs/kibana.crt
#      - SERVER_SSL_KEY=/usr/share/kibana/config/certs/kibana.key
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjpOdm5LLTluUVNsLUZicXl3bU1vdk5R
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml  # 挂载自定义配置文件
    networks:
      - elastic-net
    depends_on:
      - elasticsearch

  elasticsearch:  # 配套的Elasticsearch服务
    image: elasticsearch:8.18.0
    ports:
      - "9210:9200"
      - "9211:9201"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD=mypassword  # 设置Elasticsearch超级用户的密码
      - xpack.security.enabled=true       # 启用安全模块
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elastic-net

volumes:
  es_data:

networks:
  elastic-net:
    driver: bridge