services:
  redis_testing:
    image: redis:latest
    container_name: redis_testing
    ports:
      - "5001:6379"
    volumes:
      - ./data:/data
    command: redis-server --requirepass mypassword # 仅仅设置密码
#    command: redis-server --port 6379 --requirepass password #
    networks:
      - redis_net

networks:
  redis_net:
    driver: bridge