version: '3.8'

services:
  redis-master:
    image: redis:7.2
    container_name: redis-master
    command: redis-server --requirepass masterpassword --masterauth slavepassword
    ports:
      - "6379:6379"
    volumes:
      - redis-master-data:/data
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  redis-slave1:
    image: redis:7.2
    container_name: redis-slave1
    command: >
      redis-server
      --requirepass slavepassword
      --masterauth masterpassword
      --replicaof redis-master 6379
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
    volumes:
      - redis-slave1-data:/data
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "slavepassword", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  redis-slave2:
    image: redis:7.2
    container_name: redis-slave2
    command: >
      redis-server
      --requirepass slavepassword
      --masterauth masterpassword
      --replicaof redis-master 6379
    ports:
      - "6381:6379"
    depends_on:
      - redis-master
    volumes:
      - redis-slave2-data:/data
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "slavepassword", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  redis-master-data:
  redis-slave1-data:
  redis-slave2-data:

networks:
  redis-network:
    driver: bridge