services:
  redis-master:
    image: redis:7.2
    container_name: redis-master
    command: >
      redis-server
      --requirepass mypassword
      --masterauth mypassword
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 5
    ports:
      - "5010:6379"
    volumes:
      - redis-master-data:/data # ok
#      - /usr/local/redis/data:/data # 存储位置挂载到容器内其他目录 ok
#      - ./redis-master-data:/data # 存储位置挂载到宿主机 failed
#      - /d/workspace_server/untitled/redis_cluster/redis-master-data:/data
    networks:
      - redis-network

  redis-slave1:
    image: redis:7.2
    container_name: redis-slave1
    command: >
      redis-server
      --requirepass mypassword
      --masterauth mypassword
      --replicaof redis-master 6379
    ports:
      - "5011:6379"
    volumes:
#      - redis-slave1-data:/data # ok
#      - /usr/local/redis/data:/data # 存储位置挂载到容器内其他目录 ok
#      - /redis-slave1-data:/data # 存储位置挂载到宿主机 failed
      - /d/workspace_server/untitled/redis_cluster/redis-slave1-data:/data
    depends_on:
      - redis-master
    networks:
      - redis-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "mypassword", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3

  redis-slave2:
    image: redis:7.2
    container_name: redis-slave2
    command: >
      redis-server
      --requirepass mypassword
      --masterauth mypassword
      --replicaof redis-master 6379
    ports:
      - "5012:6379"
    volumes:
#      - redis-slave2-data:/data # ok
#      - /usr/local/redis/data:/data # 存储位置挂载到容器内其他目录 ok
#      - ./redis-slave2-data:/data # 存储位置挂载到宿主机 failed
      - /d/workspace_server/untitled/redis_cluster/redis-slave2-data:/data
    depends_on:
      - redis-master
    networks:
      - redis-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "mypassword", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  redis-master-data:
    - d://workspace_server/untitled/redis_cluster/redis-master-data:/data
#  redis-slave1-data:
#  redis-slave2-data:
#  /d/workspace_server/untitled/redis_cluster/redis-master-data/:
#  /d/workspace_server/untitled/redis_cluster/redis-slave1-data/:
#  /d/workspace_server/untitled/redis_cluster/redis-slave2-data/:

networks:
  redis-network:
    driver: bridge
    attachable: true