services:
  redis_master:
    image: redis:latest
    container_name: redis_master
    ports:
      - "55001:6379"
    volumes:
      - ./data/master:/data
#      - ./redis.conf:/data/redis.conf  # 映射配置文件
#    command: redis-server /redis.conf
    command: redis-server --port 6379 --requirepass password
    networks:
      - redis_net

  redis_slave_1:
    image: redis:latest
    container_name: redis_slave_1
    ports:
      - "55002:6379"
    volumes:
      - ./data/slave:/data
#      - ./redis.conf:/data/redis.conf  # 映射配置文件
#    command: redis-server --slaveof redis_master 6379
    command: redis-server --port 6379 --slaveof redis_master 6379 --masterauth password --port 6379 --requirepass password
    networks:
      - redis_net

  redis_slave_2:
    image: redis:latest
    container_name: redis_slave_2
    ports:
      - "55003:6379"
    volumes:
      - ./data/slave:/data
#      - ./redis.conf:/data/redis.conf  # 映射配置文件
#    command: redis-server --slaveof redis_master 6379
    command: redis-server --port 6379 --slaveof redis_master 6379 --masterauth password --port 6379 --requirepass password
    networks:
      - redis_net

#volumes:
#  redis_master-data: {}
#  redis-slave1-data: {}
#  redis-slave2-data: {}

networks:
  redis_net:
    driver: bridge